key_openai = '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'

prompt_hilex = 'Rephrase the given legal text in simpler language and active voice, while maintaining the original meaning. If the input is not a clause, return the message *NOT A CLAUSE*. Use the same language as the original input. Input:'

prompt_hilex2 = 'Rewrite the following legal clause in simpler language, using active voice while retaining the original meaning. Use the same language as the input. Input:'

prompt_test = 'Escreva um poema sobre:'

prompt_test2 = 'Escreva uma mensagem curta sobre:'
